generator:
  class: sfDoctrineGenerator
  param:
    config:
      form:
        class: sfGuardUserAdminForm
        display:
          "NONE":                   [username, password, password_again, Profile]
          "Permissions and groups": [is_active, is_super_admin, is_super_admin, is_super_admin]
