test:
  repository:
    type: svn
    svn:
      url: file:///%SF_ROOT_DIR%/test/fixtures/svn
      xml: %SF_ROOT_DIR%/cache/svn_test.xml
      diff: %SF_ROOT_DIR%/cache/svn_test_diff
    git:
      local_repository: %SF_ROOT_DIR%/test/fixtures/git
      local_log_file: %SF_ROOT_DIR%/cache/gitLogFile
      separator: '|'
      prefix: _revision_
      suffix: <<_END_>>

demo:
  repository:
    type: svn
    svn:
      url: file:///%SF_ROOT_DIR%/test/fixtures/svn
      xml: %SF_ROOT_DIR%/cache/svn_test.xml
      diff: %SF_ROOT_DIR%/cache/svn_test_diff
    git:
      local_repository: %SF_ROOT_DIR%/test/fixtures/git
      local_log_file: %SF_ROOT_DIR%/cache/gitLogFile
      separator: '|'
      prefix: _revision_
      suffix: <<_END_>>

phpcollabdev:
  repository:
    type: svn
    svn:
      url: file:///%SF_ROOT_DIR%/test/fixtures/svn
      xml: %SF_ROOT_DIR%/cache/svn_test.xml
      diff: %SF_ROOT_DIR%/cache/svn_test_diff
    git:
      local_repository: %SF_ROOT_DIR%/test/fixtures/git
      local_log_file: %SF_ROOT_DIR%/cache/gitLogFile
      separator: '|'
      prefix: _revision_
      suffix: <<_END_>>
      
dev:
  repository:
    type: svn
    svn:
      url: file:///%SF_ROOT_DIR%/test/fixtures/svn
      xml: %SF_ROOT_DIR%/cache/svn_test.xml
      diff: %SF_ROOT_DIR%/cache/svn_test_diff
    git:
      local_repository: %SF_ROOT_DIR%/test/fixtures/git
      local_log_file: %SF_ROOT_DIR%/cache/gitLogFile
      separator: '|'
      prefix: _revision_
      suffix: <<_END_>>
  
all:
  itemperpage:
    users: 5
  statuses:
    types:
      new: new
      invalid: invalid
      closed: closed
      assigned: assigned
  sf_guard_plugin:
    remember_key_expiration_age:  2592000   # 30 days in seconds
    remember_cookie_name:         phpcollabRememberMe
  repository:
    type: svn
    svn:
      url: file:///%SF_ROOT_DIR%/test/fixtures/svn
      xml: %SF_ROOT_DIR%/cache/svn_test.xml
      diff: %SF_ROOT_DIR%/cache/svn_test_diff
    git:
      local_repository: %SF_ROOT_DIR%/test/fixtures/git
      local_log_file: %SF_ROOT_DIR%/cache/gitLogFile
      separator: '|'
      prefix: _revision_
      suffix: <<_END_>>
