all:
  itemperpage:
    users: 5
  statuses:
    types:
      new: new
      invalid: invalid
      closed: closed
      assigned: assigned
  sf_guard_plugin:
    remember_key_expiration_age:  2592000   # 30 days in seconds
    remember_cookie_name:         phpcollabRememberMe
