# default rules
#homepage:
#  url:   /:sf_culture
#  param: { module: default, action: index, sf_culture: en}

sf_guard_signin:
  url:   /:sf_culture/login
  param: { module: sfGuardAuth, action: signin}
  requirements:
    sf_culture: (?:en|it)

sf_guard_signout:
  url:   /:sf_culture/logout
  param: { module: sfGuardAuth, action: signout}
  requirements:
    sf_culture: (?:en|it)

sf_guard_password:
  url:   /:sf_culture/request_password
  param: { module: sfGuardAuth, action: password}
  requirements:
    sf_culture: (?:en|it)

sf_guard_group:
  url:   /:sf_culture/sfGuardGroup
  param: { module: sfGuardGroup, action: index }
  requirements:
    sf_culture: (?:en|it)

sf_guard_group_edit:
  url:     /:sf_culture/sfGuardGroup/:id/edit
  class:   sfDoctrineRoute
  options: { model: sfGuardGroup, type: object }
  param:   { module: sfGuardGroup, action: edit }
  requirements:
    id: \d+
    sf_culture: (?:en|it)

sf_guard_group_new:
  url:     /:sf_culture/sfGuardGroup/new
  class:   sfDoctrineRoute
  options: { model: sfGuardGroup, type: object }
  param:   { module: sfGuardGroup, action: new }
  requirements:
    sf_culture: (?:en|it)

sf_guard_group_delete:
  url:     /:sf_culture/sfGuardGroup/:id/delete
  class:   sfDoctrineRoute
  options: { model: sfGuardGroup, type: object }
  param:   { module: sfGuardGroup, action: delete }
  requirements:
    id: \d+
    sf_culture: (?:en|it)

sf_guard_permission:
  url:   /:sf_culture/sfGuardPermission
  param: { module: sfGuardPermission, action: index }
  requirements:
    sf_culture: (?:en|it)

sf_guard_permission_edit:
  url:     /:sf_culture/sfGuardPermission/:id/edit
  class:   sfDoctrineRoute
  options: { model: sfGuardPermission, type: object }
  param:   { module: sfGuardPermission, action: edit }
  requirements:
    id: \d+
    sf_culture: (?:en|it)

sf_guard_permission_new:
  url:     /:sf_culture/sfGuardPermission/new
  class:   sfDoctrineRoute
  options: { model: sfGuardPermission, type: object }
  param:   { module: sfGuardPermission, action: new }
  requirements:
    sf_culture: (?:en|it)

sf_guard_permission_delete:
  url:     /:sf_culture/sfGuardPermission/:id/delete
  class:   sfDoctrineRoute
  options: { model: sfGuardPermission, type: object }
  param:   { module: sfGuardPermission, action: delete }
  requirements:
    id: \d+
    sf_culture: (?:en|it)

sf_guard_user:
  url:   /:sf_culture/idUsers
  param: { module: sfGuardUser, action: index }
  requirements:
    sf_culture: (?:en|it)

sf_guard_user_edit:
  url:     /:sf_culture/sfGuardUser/:id/edit
  class:   sfDoctrineRoute
  options: { model: sfGuardUser, type: object }
  param:   { module: sfGuardUser, action: edit }
  requirements:
    id: \d+
    sf_culture: (?:en|it)

sf_guard_user_new:
  url:     /:sf_culture/sfGuardUser/new
  class:   sfDoctrineRoute
  options: { model: sfGuardUser, type: object }
  param:   { module: sfGuardUser, action: new }
  requirements:
    sf_culture: (?:en|it)

sf_guard_user_delete:
  url:     /:sf_culture/sfGuardUser/:id/delete
  class:   sfDoctrineRoute
  options: { model: sfGuardUser, type: object }
  param:   { module: sfGuardUser, action: delete }
  requirements:
    id: \d+
    sf_culture: (?:en|it)

sf_guard_user_show:
  url:     /:sf_culture/sfGuardUser/:id/show
  class:   sfDoctrineRoute
  options: { model: sfGuardUser, type: object }
  param:   { module: sfGuardUser, action: show }
  requirements:
    id: \d+
    sf_culture: (?:en|it)

homepage:
  url:   /:sf_culture
  param: { module: idDashboard, action: index, sf_culture: en}
  requirements:
    sf_culture: (?:en|it)

default_index:
  url:   /:sf_culture/:module
  param: { action: index }
  requirements:
    sf_culture: (?:en|it)

default:
  url:   /:sf_culture/:module/:action/*
  requirements:
    sf_culture: (?:en|it)