<?php
/**
 * This file is part of the phpCollab3 package.
 * (c) 2009 Ideato s.r.l. <phpcollab@ideato.it>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 * PluginPriorityTable.class.php
 *
 * @package    phpCollab3
 * @subpackage idProjectManagmentPlugin Model
 */

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    phpCollab3
 * @subpackage idProjectManagmentPlugin Model
 */
class PluginPriorityTable extends Doctrine_Table
{
  public function getPrioritiesOrderByPositionQuery()
  {
    return Doctrine_Query::create()->
            from('Priority pr')->
            orderBy('pr.position');
  }

  public function retrieveHighestPosition()
  {
    $priority = Doctrine_Query::create()
                      ->from('Priority pr')
                      ->orderBy('pr.position DESC')
                      ->fetchOne();

    if ($priority)
    {
      return $priority->getPosition();
    }

    return -1;
  }

}