<?php
/**
 * This file is part of the phpCollab3 package.
 * (c) 2009 Ideato s.r.l. <phpcollab@ideato.it>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 * PluginStatusTable.class.php
 *
 * @package    phpCollab3
 * @subpackage idProjectManagmentPlugin Model
 */

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    phpCollab3
 * @subpackage idProjectManagmentPlugin Model
 */
class PluginStatusTable extends Doctrine_Table
{
   public function getStatusesOrderByPositionQuery()
  {
    return Doctrine_Query::create()->
            from('Status s')->
            orderBy('s.position');
  }

  public function retrieveHighestPosition()
  {
    $status = Doctrine_Query::create()
                      ->from('Status s')
                      ->orderBy('s.position DESC')
                      ->fetchOne();

    if ($status)
    {
      return $status->getPosition();
    }

    return -1;
  }

  public function isClosedTypeById($id)
  {
    $status = Doctrine_Query::create()
                ->from('Status s')
                ->where('(s.status_type = ? OR s.status_type = ?)', array('closed', 'invalid'))
                ->addWhere('s.id = ?', $id)
                ->fetchOne();

    return (bool) $status;
  }

  public function isOpenTypeById($id)
  {
    $status = Doctrine_Query::create()
                ->from('Status s')
                ->where('s.status_type = ?', 'new')
                ->addWhere('s.id = '. $id)
                ->fetchOne();

    return (bool) $status;
  }
}