<?php
/**
 * This file is part of the phpCollab3 package.
 * (c) 2009 Ideato s.r.l. <phpcollab@ideato.it>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 * PluginIssue.class.php
 *
 * @package    phpCollab3
 * @subpackage idProjectManagmentPlugin Model
 */

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    phpCollab3
 * @author Filippo (p16) De Santis <fd@ideato.it>
 * @subpackage idProjectManagmentPlugin Model
 */
abstract class PluginIssue extends BaseIssue
{
  /**
   * magic method that return the a string of the format "#<number> <issue_title>" when an issue is printed
   *
   * @return string
   */
  public function __toString()
  {
    return '#'.$this->id.' '.$this->title;
  }

  /**
   * Cheks if an issue has at least one comment
   *
   * @return boolean
   */
  public function hasComments()
  {
    return (Doctrine::getTable('fdComment')->getQueryForListByModelAndFieldAndValue(get_class($this), 'id', $this->id)->count() > 0);
  }
}