<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginLogTimeTable extends Doctrine_Table
{
  public function getLogTimeByIssueAndProfile($issue_id, $profile_id)
  {
    return Doctrine_Query::create()
            ->from('LogTime lt')
            ->leftJoin('lt.issue i')
            ->leftJoin('lt.profile p')
            ->addWhere('lt.profile_id = ? ',$profile_id)
            ->addWhere('lt.issue_id = ? ',$issue_id)
            ->execute();
  }
}