<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginfdComment extends BasefdComment
{
  public function getProfile()
  {
    return Doctrine::getTable('fdComment')->getProfileForComment($this->profile_id);
  }

}