<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginfdCommentTable extends Doctrine_Table
{
  public function getQueryForComments()
  {
    return Doctrine_Query::create()
            ->from('fdComment fdc');
  }

  public function getQueryForCommentsByModel($model)
  {
    return $this->getQueryForComments()
            ->where('fdc.model = ?', $model);
  }

  public function getQueryForCommentsByModelAndModelField($model, $field)
  {
    return $this->getQueryForCommentsByModel($model)
            ->andWhere('fdc.model_field = ?', $field);
  }

  public function getQueryForListByModelAndFieldAndValue($model, $field, $value)
  {
    return $this->getQueryForCommentsByModelAndModelField($model, $field)
            ->andWhere('fdc.model_field_value = ?', $value)
            ->orderBy('fdc.created_at DESC');
  }

  public function getQueryForCommentsByUserId($user_id)
  {
    return $this->getQueryForComments()
            ->andWhere('fdc.user_id = ?', $user_id);
  }

  public function getQueryForCommentsByUserIdAndModel($user_id, $model_name)
  {
    return $this->getQueryForCommentsByModel($model_name)
            ->andWhere('fdc.user_id = ?', $user_id);
  }

  public function getQueryForCommentsByUserIdAndModelAndModelFieldValue($user_id, $model_name, $model_name_value)
  {
    return $this->getQueryForCommentsByUserIdAndModel($user_id, $model_name)
            ->andWhere('fdc.model_field_value = ?', $model_name_value);
  }

  public function getQueryForUsersByModelAndModelFieldValue($model_name, $model_name_value)
  {
    $config = sfConfig::get('sf_confing_comments_plugin_Profile', array());
    $q = new Doctrine_RawSql();
    $q->select('{p.*}')
      ->from(sfInflector::underscore($config['class_name']).' as p LEFT JOIN fd_comment as fd ON p.'.$config['class_id'].' = fd.user_id')
      ->addComponent('p', $config['class_name'].' p')
      ->where('fd.model = ?', $model_name)
      ->andWhere('fd.user_id = p.'.$config['class_id'])
      ->andWhere('fd.model_field_value = ?', $model_name_value)
      ->groupBy('fd.user_id');

    return $q;
  }

  public function getUserForComment($user_id)
  {
    $config = sfConfig::get('sf_confing_comments_plugin_Profile', array());
    
    return Doctrine_Query::create()
            ->from($config['class_name'].' as p')
            ->where('p.'.$config['class_id'].' = ? ', $user_id)
            ->fetchOne();
  }
}