<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginfdComment extends BasefdComment
{
  public function getUser()
  {
    return Doctrine::getTable('fdComment')->getUserForComment($this->user_id);
  }

}