dev:
  doctrine:
    class: sfDoctrineDatabase
    param:
#      dsn: 'sqlite:%SF_CACHE_DIR%/phpcollab.db'
      dsn: 'mysql:host=localhost;dbname=phpcollab'
      username: root
      password:

demo:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'sqlite:%SF_DATA_DIR%/phpcollab_demo.db'

prod:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'sqlite:%SF_DATA_DIR%/phpcollab_demo.db'

test:
  doctrine:
    class: sfDoctrineDatabase
    param:
#      dsn: 'sqlite::memory:'
      dsn: 'sqlite:%SF_DATA_DIR%/phpcollab.db'
#dsn: 'sqlite:/tmp/sqlite-folder/phpcollab.db'
#      dsn: 'mysql:host=localhost;dbname=phpcollab'
#      username: root
#      password:

unittest:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'sqlite:%SF_DATA_DIR%/phpcollab_unit_test.db'
#dsn: 'sqlite:/tmp/sqlite-folder/phpcollab_unit_test.db'
#      dsn: 'sqlite:memory'

all:
  doctrine:
    class: sfDoctrineDatabase