<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddEstimatedTimeForIssue extends Doctrine_Migration
{
  public function up()
  {
    $this->addColumn('issue', 'estimated_time', 'float');
  }

  public function down()
  {
    $this->removeColumn('issue', 'estimated_time');
  }

}