<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ApplyForeignKeyConstraints extends Doctrine_Migration
{
	public function up()
	{
		$this->createForeignKey('issue', array('local' => 'tracker_id', 'foreign' => 'id', 'foreignTable' => 'tracker',
        'onUpdate' => NULL, 'onDelete' => 'SET NULL', 'name' => 'issue_tracker_id'));

    $this->createForeignKey('projects_trackers', array('local' => 'project_id', 'foreign' => 'id', 'foreignTable' => 'project',
        'onUpdate' => NULL, 'onDelete' => 'CASCADE', 'name' => 'projects_trackers_project_id'));

    $this->createForeignKey('projects_trackers', array('local' => 'tracker_id', 'foreign' => 'id', 'foreignTable' => 'tracker',
        'onUpdate' => NULL, 'onDelete' => 'CASCADE', 'name' => 'projects_trackers_tracker_id'));

	}

	public function down()
	{
		$this->dropForeignKey('issue', 'issue_tracker_id');
		$this->dropForeignKey('projects_trackers', 'projects_trackers_project_id');
		$this->dropForeignKey('projects_trackers', 'projects_trackers_tracker_id');

	}
}