<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddLogTime extends Doctrine_Migration
{
	public function up()
	{
		$this->createTable('log_time',
      array(
        'id' => array('type' => 'integer', 'primary' => true, 'autoincrement' => true, 'length' => 2147483647),
        'created_at' => array('type' => 'timestamp', 'length' => 25),
        'issue_id' => array('type' => 'integer', 'length' => 2147483647),
        'profile_id' => array('type' => 'integer', 'length' => 2147483647),
        'log_time' => array('type' => 'float', 'length' => 2147483647)),
      array('indexes' => array(), 'primary' => array(0 => 'id')));
	}

	public function down()
	{
		$this->dropTable('log_time');
	}
}