<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddProjectEndDateColumn extends Doctrine_Migration
{
	public function up()
	{
    $this->addColumn('project', 'end_date', 'timestamp', array('length' => 25));
	}

	public function down()
	{
    $this->removeColumn('project', 'end_date');
	}
}