<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddCommentsPluginModel extends Doctrine_Migration
{
	public function up()
	{
    $this->createTable('fd_comment',
      array('id' => array('type' => 'integer', 'primary' => true, 'autoincrement' => true, 'length' => 4),
            'title' => array('type' => 'string', 'notnull' => true, 'length' => 512),
            'body' => array('type' => 'string', 'notnull' => true, 'length' => 3000),
            'profile_id' => array('type' => 'integer', 'length' => 2147483647),
            'model' => array('type' => 'string', 'length' => 255),
            'model_field' =>  array('type' => 'string', 'length' => 255),
            'model_field_value' => array('type' => 'integer', 'length' => 2147483647),
            'created_at' => array('type' => 'timestamp', 'length' => 25)),
      array('indexes' => array('profileidindex' =>  array( 'fields' =>  array( 0 => 'profile_id',  ), )),
            'primary' => array(0 => 'id')));

    $this->addColumn('project', 'starting_date', 'timestamp', array('length' => 25));
    $this->addColumn('milestone', 'estimated_time', 'float', array('length' => 2147483647));
    $this->dropForeignKey('comment', 'comment_issue_id');
    $this->dropForeignKey('comment', 'comment_profile_id');
    $this->dropTable('comment');

    $this->createTable('message',
      array('id' => array('type' => 'integer', 'primary' => true, 'autoincrement' => true, 'length' => 4),
            'title' => array('type' => 'string', 'notnull' => true, 'length' => 512),
            'body' => array('type' => 'string', 'notnull' => true, 'length' => 3000),
            'profile_id' => array('type' => 'integer', 'length' => 2147483647),
            'project_id' => array('type' => 'integer', 'length' => 2147483647),
            'created_at' => array('type' => 'timestamp', 'length' => 25)),
      array('indexes' => array('profileidindex' =>  array( 'fields' =>  array( 0 => 'profile_id',  ), )),
            'primary' => array(0 => 'id')));
    $this->createForeignKey('message', array('local' => 'project_id',
                                             'foreign' => 'id',
                                             'foreignTable' => 'project',
                                             'onUpdate' => NULL,
                                             'onDelete' => 'CASCADE',
                                             'name' => 'comment_project_id'));
    $this->createForeignKey('message', array('local' => 'profile_id',
                                             'foreign' => 'id',
                                             'foreignTable' => 'profile',
                                             'onUpdate' => NULL,
                                             'onDelete' => 'SET NULL',
                                             'name' => 'comment_profile_id'));

	}

	public function down()
	{
    $this->dropTable('fd_comment');
    $this->removeColumn('project', 'starting_date');
    $this->removeColumn('project', 'estimated_time');
    $this->createTable('comment',
      array('id' => array('type' => 'integer', 'primary' => true, 'autoincrement' => true, 'length' => 2147483647),
            'issue_id' => array('type' => 'integer', 'length' => 2147483647),
            'profile_id' => array('type' => 'integer', 'length' => 2147483647),
            'body' => array('type' => 'string', 'length' => 1000),
            'created_at' => array('type' => 'timestamp', 'length' => 25)),
      array('indexes' => array(), 'primary' => array(0 => 'id')));
    $this->createForeignKey('comment', array('local' => 'issue_id',
                                             'foreign' => 'id',
                                             'foreignTable' => 'issue',
                                             'onUpdate' => NULL,
                                             'onDelete' => 'CASCADE',
                                             'name' => 'comment_issue_id'));
    $this->createForeignKey('comment', array('local' => 'profile_id',
                                             'foreign' => 'id',
                                             'foreignTable' => 'profile',
                                             'onUpdate' => NULL,
                                             'onDelete' => 'SET NULL',
                                             'name' => 'comment_profile_id'));
    $this->dropForeignKey('message', 'message_profile_id');
    $this->dropForeignKey('message', 'comment_project_id');
    $this->dropTable('message');
	}
}