<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddStatusTypeStatusPositionPriorityPosition extends Doctrine_Migration
{
  public function up()
	{
    $this->addColumn('status', 'status_type', 'string', array('length' => 64, 'default'=> null));
    $this->addColumn('status', 'position', 'integer', array('default'=> null));
    $this->addColumn('priority', 'position', 'integer', array('default'=> null));
	}

  public function postUp()
  {
    $q = Doctrine_Query::create()
          ->from('Status s');

    $statuses = $q->execute();

    $i = 0;
    $status_types = array_keys(sfConfig::get('app_statuses_types'));
    foreach ($statuses as $status)
    {
      $status->setPosition($i);
      $status->setStatusType($status_types[0]);
      $status->save();
      $i++;
    }

    $q = Doctrine_Query::create()
          ->from('Priority p');

    $priorities = $q->execute();

    $i = 0;
    foreach ($priorities as $priority)
    {
      $priority->setPosition($i);
      $priority->save();
      $i++;
    }
  }

  public function preDown()
  {
    $q = Doctrine_Query::create()
          ->from('Status s');

    $statuses = $q->execute();
    foreach ($statuses as $status)
    {
      $status->setPosition(null);
      $status->setStatusType(null);
      $status->save();
    }

    $q = Doctrine_Query::create()
          ->from('Priority p');

    $priorities = $q->execute();
    foreach ($priorities as $priority)
    {
      $priority->setPosition(null);
      $priority->save();
    }
  }

	public function down()
	{
    $this->removeColumn('status', 'status_type');
    $this->removeColumn('status', 'position');
    $this->removeColumn('priority', 'position');
	}
}
