<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginMessage extends BaseMessage
{
  public function setUp()
  {
    parent::setUp();
    $this->addListener(new EventLogDoctrineListener());
  }

  public function getLastCommentDate()
  {
    if ($last_comment = Doctrine::getTable('Message')->getLastComment($this->id))
    {
      return $last_comment->created_at;
    }
    return $this->created_at;
  }
}