<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginMessageTable extends Doctrine_Table
{
  public function getQueryForProjectMessages($project_id)
  {
    return Doctrine_Query::create()
            ->from('Message m')
            ->leftJoin('m.UserProfile up')
            ->leftJoin('m.project p')
            ->where('m.project_id = '. $project_id)
            ->orderBy('m.created_at DESC');
  }

  public function getLastComment($id)
  {
    return Doctrine::getTable('fdComment')->
             getQueryForListByModelAndFieldAndValue('Message', 'id', $id)->
             orderBy('created_at DESC')->
             fetchOne();
  }
}