<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginLogTimeTable extends Doctrine_Table
{
  public function getLogTimeForIssueByUser($issue_id, $user_id)
  {
    return $this->getQueryForLogtimesForIssueByUser($issue_id, $user_id)->
                  select('SUM(lt.log_time) as logtimes')->
                  execute(array(), Doctrine::HYDRATE_ARRAY);
  }

  protected function getQueryForLogtimesForIssueByUser($issue_id, $user_id)
  {
    return Doctrine_Query::create()
            ->from('LogTime lt')
            ->leftJoin('lt.issue i')
            ->leftJoin('lt.sfGuardUser p')
            ->addWhere('lt.user_id = ? ',$user_id)
            ->addWhere('lt.issue_id = ? ',$issue_id);
  }

  public function getLogTimeByIssueAndUser($issue_id, $user_id)
  {
    return $this->getQueryForLogtimesForIssueByUser($issue_id, $user_id)
                ->execute();
  }

  public function getQueryForAllLogTimes()
  {
    return Doctrine_Query::create()
            ->from('LogTime lt')
            ->leftJoin('lt.issue i')
            ->leftJoin('lt.sfGuardUser p')
            ->orderBy('lt.created_at DESC');
  }

  public function getQueryForAllLogTimeFromProject($project_id)
  {
    return $this->getQueryForAllLogTimes()
            ->where('i.project_id = ? ', $project_id);
  }

  public function getQueryForAllLogTimeFromProjectAndIssue($project_id, $issue_id)
  {
    return $this->getQueryForAllLogTimes()
            ->where('i.project_id = ? ', $project_id)
            ->andWhere('i.id = ? ', $issue_id);
  }

  public function getQueryForUserLogTimeFromProjectAndIssue($user_id, $project_id, $issue_id)
  {
    return $this->getQueryForAllLogTimeFromProjectAndIssue($project_id, $issue_id)
            ->andWhere('p.id = ? ', $user_id);
  }

  public function getLogtimeForProjectByUser($project_id)
  {
    return $this->getQueryForAllLogTimeFromProject($project_id)
            ->execute();
  }
}