<?php
/**
 * This file is part of the phpCollab3 package.
 * (c) 2009 Ideato s.r.l. <phpcollab@ideato.it>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 * PluginMilestone.class.php
 *
 * @package    phpCollab3
 * @subpackage idProjectManagmentPlugin Model
 */


/**
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    phpCollab3
 * @author Filippo (p16) De Santis <fd@ideato.it>
 * @subpackage idProjectManagmentPlugin Model
 */
abstract class PluginMilestone extends BaseMilestone
{
  /**
   * Magic method to return the milestone title when a milestone object is printed
   *
   * @return <type>
   */
  public function __toString()
  {
    return $this->title;
  }

  public function setUp()
  {
    parent::setUp();
    $this->addListener(new EventLogDoctrineListener());
  }
}