<?php
/**
 * This file is part of the phpCollab3 package.
 * (c) 2009 Ideato s.r.l. <phpcollab@ideato.it>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 * PluginProfileTable.class.php
 *
 * @package    phpCollab3
 * @subpackage idProjectManagmentPlugin Model
 */


/**
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    phpCollab3
 * @subpackage idProjectManagmentPlugin Model
 */
//class PluginProfileTable extends Doctrine_Table
//{
//  /**
//   * Returns the Doctrine_Query object that contains the query for retriving all the user of the system but those having is_duper_admin flag at true.
//   *
//   * @return Doctrine_Query
//   */
//  public function retrieveQueryForAllButSuperAdmin()
//  {
//    return Doctrine_Query::create()
//            ->from('Profile p')
//            ->leftJoin('p.User u')
//            ->where('u.is_super_admin = 0');
//  }
//
//  public function getQueryForProjectUsers($project_id)
//  {
//    return Doctrine_Query::create()
//            ->from('Profile p')
//            ->leftJoin('p.User u')
//            ->leftJoin('p.projects ps')
//            ->where('ps.id = ?', $project_id);
//  }
//}