<?php
/**
 * This file is part of the phpCollab3 package.
 * (c) 2009 Ideato s.r.l. <phpcollab@ideato.it>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 * PluginProjectUser.class.php
 *
 * @package    phpCollab3
 * @subpackage idProjectManagmentPlugin Model
 */


/**
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    phpCollab3
 * @subpackage idProjectManagmentPlugin Model
 */
abstract class PluginProjectUser extends BaseProjectUser
{
  public static $roles = array('admin' => 1,
                               'developer' => 2,
                               'project manager' => 3,
                               'customer' => 4);

  public static function getRoleByProfileIdAndProjectId($profile_id, $project_id)
  {
    $code = Doctrine::getTable('ProjectUser')->getRoleByProfileIdAndProjectId($profile_id, $project_id);
    if($code)
    {
      $roles = array_flip(self::$roles);
      return $roles[$code];
    }
  }
}